name: Trigger OBS Build

on:
  push:
    tags:
      - "v*"

jobs:
  obs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger OBS service
        run: |
          curl -X POST \
            -u itachi_re:${{ secrets.OBS_TOKEN }} \
            "https://api.opensuse.org/source/home:itachi_re/brave-browser?cmd=runservice"
